export {default as Home } from "./Home"
export {default as QuickRead } from "./QuickRead"
export {default as OlderPosts } from "./OlderPosts"
export {default as PopularTags } from "./PopularTags"
export {default as NewsLetter } from "./NewsLetter"
export {default as Footer } from "./Footer"
